### ISSUE TITLE
Yo long time no see, I'm testing out GitCash for a friend! Thought your mac cursors deserved a tip :)

### ISSUE THREAD

**Issue by owenlord** [daviddarnes/mac-cursors#11]
@GitCash send .0095 bch to @daviddarnes

**Comment by GitCash** [comment]
Hey **daviddarnes**, user **owenlord** tipped you **9500 bits** in Bitcoin Cash ( ~ **$5.0065** ).

*[Click here to claim it!](https://gitcash.io/claim/daviddarnes)*

You can also add the "thumbs down" reaction to **owenlord**'s comment above to prevent future tips.

**Comment by daviddarnes** [comment]
Hey @owenlord! Oh thanks very much, not sure it's working though. I created an account on GitCash via the link but nothing appearing in the balance?
