### ISSUE TITLE
Update cursors to match macOS Ventura

### ISSUE THREAD

**Issue by qo4on** [daviddarnes/mac-cursors#17]
Thank you so much for the cursors! I have a few questions:
1. The 35x35 resolution corresponds to the smallest cursor in MacOS, right?
2. Does the position and scale of the cursors on the 35x35 canvas match the actual position and scale in MacOS or is it arbitrarily chosen?
3. Is there any information about where the Hot Spot is located for each cursor?
4. Is it possible to get svg cursors with shadow?
5. Animated cursors should probably have an svg file for each animation frame, is it possible to get them too?

**Comment by daviddarnes** [comment]
Hey, no problem! Answers below:
1. I think so? I think I adjusted the size in CSS to match my actual cursor size
2. The position and scale is just related to the SVG files, I didn’t see how they’re set in the code
3. Afraid not, I didn’t see the code implementation. I literally copied them from an OS level source folder
4. Maybe! Though these were lifted directly from the source folder, so I assume the shadows are applied after in the code. That’s similar to what I’m doing, but with CSS
5. Again I think that’s applied with code, so state can be changed without editing the direct source

**Comment by qo4on** [comment]
Thanks for the reply. Do you know what code was used for the animation? The thing is that in addition to the rotation, which is not difficult to replicate in the code, there is also used color gradient animation. And I can't tell by eye which animation is used.

**Comment by daviddarnes** [comment]
No idea I’m afraid. Like I said I just copied the SVGs out of a folder, I didn’t look at any code

**Comment by qo4on** [comment]
Ok, thank you.

**Comment by qo4on** [comment]
Can you do the same for macOS Ventura 13 cursors? They are very different:
https://support.apple.com/en-za/guide/mac-help/mh35695/mac

**Comment by daviddarnes** [comment]
Will do @qo4on. I've not had the time to update these since originally doing them. Sorry about that.

**Comment by daviddarnes** [comment]
All fully update to the latest OS @qo4on https://mac-cursors.netlify.app

**Comment by qo4on** [comment]
Are you sure these are Ventura 13 cursors?
![image](https://user-images.githubusercontent.com/35609308/232114135-41d745f7-7bab-451c-b44f-5db4c700c9b5.png)

**Comment by daviddarnes** [comment]
@qo4on not entirely sure what you're sharing here, can you provide more context? These icons are lifted straight out of the official Apple MacOS Sketch library files, so they should be spot on

**Comment by qo4on** [comment]
As far as I can see [the Ventura 13 Not allowed cursor](https://support.apple.com/en-za/guide/mac-help/mh35695/mac) should look like this:
![image](https://user-images.githubusercontent.com/35609308/232607930-818b6bd1-c0fd-4d8a-8038-4cf0d337f1be.png)
But yours is different:
![image](https://user-images.githubusercontent.com/35609308/232608041-23676199-d249-4e65-b4ac-15c93212c9ee.png)

**Comment by daviddarnes** [comment]
@qo4on that appears to be a mistake. If you hover over the `notallowed` item [on my page](https://mac-cursors.netlify.app) you'll see the same cursor icon appears as I've shown, that means when the CSS value `no-drop` (or `not-allowed`) is applied to the `cursor` property it'll show this icon. The cross shaped icon is either a mistake or an icon that can't be accessed

**Comment by qo4on** [comment]
You're probably right.
In the last version of your cursors the resolution was 35x35, why has it changed to 32x32 now?

**Comment by daviddarnes** [comment]
Once again to match the sizing that's been lifted out of the Apple macOS source file. Also 32 is a much easier number to scale than 35
